name: project_review
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  domain:
    path: domain
  data:
    path: data
  common:
    path: common

  # Add package

  bloc: ^8.1.2
  get_it: ^7.6.4
  injectable: ^2.1.2
  equatable: ^2.0.5
  injectable_generator: ^2.1.6
  build_runner: ^2.4.6
  flutter_bloc: ^8.1.3
  dio: ^5.2.1+1
  google_sign_in: ^6.1.6
  shared_preferences: ^2.2.0
  firebase_core: ^2.14.0
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/
    - assets/images/
    - assets/animations/
    - assets/tiles/

  fonts:
    - family: Livvic
      fonts:
        - asset: assets/fonts/Livvic-Regular.ttf
        - asset: assets/fonts/Livvic-Medium.ttf
        - asset: assets/fonts/Livvic-Bold.ttf
        - asset: assets/fonts/Livvic-SemiBold.ttf

    - family: LemonDays
      fonts:
        - asset: assets/fonts/Lemon_Days.ttf
